// <auto-generated />
using BeadsInventory.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeadsInventory.Migrations.Bead
{
    [DbContext(typeof(BeadContext))]
    partial class BeadContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("BeadsInventory.Models.Bead", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color");

                    b.Property<string>("Material");

                    b.Property<decimal>("Price_Point");

                    b.Property<int>("Quantity");

                    b.Property<string>("Shape");

                    b.Property<int>("Size_MM");

                    b.HasKey("ID");

                    b.ToTable("Bead");
                });
#pragma warning restore 612, 618
        }
    }
}
